hash_text/urls.py
from django.contrib import admin
from django.urls import path
from hashing import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('hash/<str:hash>', views.hash, name='hash'),
    path('quickhash', views.quichash, name='quickhash'),

]

hashing/models.py
from django.db import models


# Create your models here.
class Hash(models.Model):
    text = models.TextField()
    hash = models.CharField(max_length=64)

hashing/forms.py
from django import forms


class HashForm(forms.Form):
    text = forms.CharField(label='Enter Hash here:', widget=forms.Textarea)

hashing/views.py
from django.shortcuts import render, redirect
from .forms import HashForm
from .models import Hash
import hashlib
from django.http import JsonResponse


# Create your views here.
def home(request):
    if request.method == "POST":
        filled_form = HashForm(request.POST)
        if filled_form.is_valid():
            text = filled_form.cleaned_data['text']
            text_hash = hashlib.sha3_256(text.encode('utf-8')).hexdigest()
            try:
                Hash.objects.get(hash=text_hash)
            except Hash.DoesNotExist:
                hash = Hash(text=text, hash=text_hash)
                hash.save()
            return redirect('hash', hash=text_hash)
    form = HashForm()
    return render(request, 'hashing/home.html', {'form': form})


def hash(request, hash):
    hash = Hash.objects.get(hash=hash)
    return render(request, 'hashing/hash.html', {'hash': hash})


def quichash(request):
    text = request.GET['text']
    text = request.GET['text']
    return JsonResponse({'hash': hashlib.sha3_256(text.encode('utf-8')).hexdigest()})

hashing/templates/hashing/hash.html
<h2>Hash:</h2>
<h1>{{ hash.hash }}</h1>
{{ hash.text }}
<h3><a href="{% url 'home' %}">Home</a></h3>

hashing/templates/hashing/home.html
<form action="{% url 'home' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input name="submit" type="submit" value="hash">
</form>


<h2 id="quickhash"></h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $('#id_text').keyup(function () {
       text = $(this).val();

       $.ajax({
           url: '/quickhash',
           data: {'text': text},
           dataType: 'json',
           success: function (data) {
               $('#quickhash').text(data['hash']);
           }
       });
    });
</script>